test: shift-reset-3-test.soar shift-reset-3.soar
	soarunit --ui shift-reset-3-test.soar

run:
	jsoar shift-reset-3-run.soar

#test: shift_reset_3_test.txt shift_reset_3.pl
#	cat shift_reset_3_test.txt - | swipl
